version: "3"
services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    networks:
      - wp
  wordpress:
    image: wordpress:latest
    ports:
      - "${PORT:-8000}:80"
    restart: always
    depends_on:
      - db
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp
  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "9090:90"
      - "443:443"
    volumes:
      - /sessions
    networks:
      - wp
networks:
  wp:
volumes:
  db_data:
