name: DIGITALOCEAN_DEPLOY
on:
  push:
    branches: [main]
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Create .env
        run: echo 'PORT=${{secrets.PORT}}' > .env
      - name: Delete volume
        run: docker-compose down -v
      - name: Run build
        run: docker-compose up -d
